Fix compiler warning: -Werror=stringop-overflow
Convert static string array sizes in function arguments to `char *`.
Specifying a static array length in a function argument doesn't provide
any safety and the functions already check strlen() and return an error
so this is equivalent.

Example error:

	src/lib/novas.c: In function ‘grav_def’:
	src/lib/novas.c:5657:13: error: ‘make_cat_entry’ accessing 51 bytes in a region of size 6 [-Werror=stringop-overflow=]
	 5657 |             make_cat_entry ("dummy","   ",0,0.0,0.0,0.0,0.0,0.0,0.0,
	      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	 5658 |                &dummy_star);
	      |                ~~~~~~~~~~~~
	src/lib/novas.c:5657:13: note: referencing argument 1 of type ‘char *’
	src/lib/novas.c:9412:11: note: in a call to function ‘make_cat_entry’
	 9412 | short int make_cat_entry (char *star_name,
	      |           ^~~~~~~~~~~~~~

Signed-off-by: Eric Wheeler <novas-git@z.ewheeler.org>