Fix compiler warning -Werror=unused-value
The original code is intended to fix a warning, but introduces a
-Werror=unused-value warning:

	/*
	   The following three lines do nothing and are just here to prevent "unreferenced
	   formal parameter" compiler warnings.
	*/

	   mp;
	   name;
	   jd;

as follows:

	src/lib/readeph0.c:97:4: error: statement with no effect [-Werror=unused-value]
	   97 |    mp;

Change these to self-assignments (ie, mp=mp).  The compiler will
optimize them out, and at both warnings can be suppressed.

Signed-off-by: Eric Wheeler <novas-git@z.ewheeler.org>